# Generated by Django 3.1.3 on 2020-11-07 12:13

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('carrying_capacity', models.IntegerField()),
                ('vehicle_passport', models.ImageField(upload_to=users.models.user_directory_path)),
                ('driver_license', models.ImageField(upload_to=users.models.user_directory_path)),
                ('id_passport', models.ImageField(upload_to=users.models.user_directory_path)),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='users.cargotype')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='users.vehicletype')),
            ],
        ),
    ]
