# Generated by Django 3.1.3 on 2020-11-13 03:51

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cargotype_drivers_vehicletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('carrying_capacity', models.IntegerField()),
                ('vehicle_passport', models.ImageField(upload_to=users.models.user_directory_path)),
                ('driver_license', models.ImageField(upload_to=users.models.user_directory_path)),
                ('id_passport', models.ImageField(upload_to=users.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='users.cargotype')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='users.vehicletype')),
            ],
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
    ]
