# Generated by Django 3.1.3 on 2020-11-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201113_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('driver', 'driver'), ('client', 'client')], default='driver', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
