# Generated by Django 3.1.3 on 2020-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201123_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
