# Generated by Django 3.1.3 on 2021-02-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
