# Generated by Django 3.1.3 on 2020-11-07 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('cargo_comment', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram_number', models.CharField(blank=True, max_length=200, null=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_from_region', to='transportations.city')),
                ('from_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_from_region', to='transportations.region')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_to_city', to='transportations.city')),
                ('to_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_to_region', to='transportations.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_shipment_date', models.DateField()),
                ('to_shipment_date', models.DateField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('place_comment', models.TextField(blank=True, null=True)),
                ('cargo_comment', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('price', models.IntegerField()),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram_number', models.CharField(blank=True, max_length=200, null=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_from_region', to='transportations.city')),
                ('from_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_from_region', to='transportations.region')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_to_city', to='transportations.city')),
                ('to_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_to_region', to='transportations.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
