# Generated by Django 3.1.3 on 2020-11-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_region', models.CharField(max_length=150)),
                ('from_city', models.CharField(max_length=150)),
                ('to_region', models.CharField(max_length=150)),
                ('to_city', models.CharField(max_length=150)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('place_comment', models.TextField()),
                ('cargo_comment', models.TextField()),
                ('cargo_type', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('phone_number', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=200)),
                ('telegram_number', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
