# Generated by Django 3.1.3 on 2020-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0002_cargo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='place_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='telegram_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
