# Generated by Django 3.1.3 on 2021-01-20 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0003_auto_20201123_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='length',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='width',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='volume',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='transportations.region'),
        ),
    ]
