# Generated by Django 3.1.3 on 2021-01-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0004_auto_20210120_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='place_comment',
            new_name='from_place_comment',
        ),
        migrations.AddField(
            model_name='cargo',
            name='to_place_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
